language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - "pip install ."
script:
  - "python example.py --value 10 -c :12 -w 9:"
  - "python setup.py test"
  - "python -m doctest README.md"
